name: GitHub Readme Stats

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Language Card
        uses: anuraghazra/github-readme-stats-action@v2
        with:
          username: Harshkatare
          card: top-langs
